# Minimal Prompt

command_timeout = 10000

format = """
$directory$git_branch
$character
"""

[directory]
style = "bold green"
truncation_length = 3
truncate_to_repo = true
format = "[ $path ]($style)"

[git_branch]
symbol = " "
style = "bold blue"
format = "[$symbol$branch]($style)"

[git_status]
style = "bold yellow"
format = "[$all_status$ahead$behind]($style) "
ahead = "↑${count}"
behind = "↓${count}"
modified = "•"
untracked = "+"
deleted = "×"

[python]
disabled = true

[nodejs]
disabled = true

[rust]
disabled = true

[line_break]
disabled = false
